[package]
name = "physics"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.15.3", features = ["bevy_dev_tools"] }
bevy_egui = "0.33.0"
once_cell = "1.21.3"
bevy_rapier3d = { version = "0.29.0", features = [ "simd-stable", "debug-render-3d" ] }
